# -*- coding: utf-8 -*-
"""Medical AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nNjlUGhLP1JIc7D54XzDXoN-d71bcmX
"""

!pip install transformers accelerate torch gradio pillow sentencepiece --quiet

# =============================
#  SINGLE CELL AI MEDICAL SYSTEM
#  Prescription + Translation + Image Analysis
#  Using IBM Granite 3B Instruct + Gradio
# =============================

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline,
    AutoProcessor,
    AutoModelForCausalLM
)
import gradio as gr
from PIL import Image

# ------------------------------------
# 1. LOAD IBM GRANITE 3B INSTRUCT
# ------------------------------------

HF_TOKEN = "YOUR_HF_TOKEN_HERE"   # <--- IMPORTANT: PUT YOUR TOKEN HERE

# Valid Granite model (3.3B DOES NOT EXIST)
model_name = "ibm-granite/granite-3b-code-instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    token=HF_TOKEN,
    trust_remote_code=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    token=HF_TOKEN,
    trust_remote_code=True,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

llm = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    temperature=0.2,
    repetition_penalty=1.1
)

# ------------------------------------
# 2. LOAD VISION MODEL ONCE
# ------------------------------------

vision_model_name = "microsoft/git-large-coco"

processor = AutoProcessor.from_pretrained(vision_model_name)
vision_model = AutoModelForCausalLM.from_pretrained(
    vision_model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# ------------------------------------
# 3. FEATURE 1 — PRESCRIPTION GENERATOR
# ------------------------------------

def generate_prescription(symptoms, patient_age):
    prompt = f"""
You are an AI Medical Assistant. Generate a SAFE, GENERAL, NON-DIAGNOSTIC medical prescription template.
Do NOT give restricted medicines. Provide general OTC advice only.
Symptom description: {symptoms}
Patient age: {patient_age}
Output sections:
1. Possible condition (general)
2. Recommended safe OTC medicines
3. Dosage (general, age-appropriate)
4. Advice & lifestyle recommendations
5. When to see a doctor
    """

    output = llm(prompt)[0]["generated_text"]
    return output

# ------------------------------------
# 4. FEATURE 2 — INDIAN LANGUAGE TRANSLATION
# ------------------------------------

languages = {
    "Hindi": "hi",
    "Tamil": "ta",
    "Telugu": "te",
    "Kannada": "kn",
    "Malayalam": "ml",
    "Bengali": "bn",
    "Gujarati": "gu",
    "Punjabi": "pa",
    "Marathi": "mr"
}

def translate_text(text, target_lang):
    prompt = f"""
Translate the following medical text into {target_lang} language accurately and clearly:
{text}
"""
    output = llm(prompt)[0]["generated_text"]
    return output

# ------------------------------------
# 5. FEATURE 3 — IMAGE ANALYSIS
# ------------------------------------

def analyze_image(image_path):

    img = Image.open(image_path).convert("RGB")

    # Caption the image
    inputs = processor(images=img, return_tensors="pt")
    if torch.cuda.is_available():
        inputs = inputs.to("cuda")

    vision_output = vision_model.generate(**inputs, max_new_tokens=50)
    image_caption = processor.batch_decode(vision_output, skip_special_tokens=True)[0]

    prompt = f"""
You are a medical image assistant. Analyze the image safely.

Image caption: {image_caption}

Describe:
- Visible abnormalities
- Skin issues, swelling, redness, infection signs
- General observations (No diagnosis)
Provide a safe and general explanation.
    """

    response = llm(prompt)[0]["generated_text"]
    return response

# ------------------------------------
# 6. BUILD GRADIO UI
# ------------------------------------

with gr.Blocks(title="AI Medical Assistant") as app:

    gr.Markdown("# 🏥 AI Medical Prescription + Translation + Image Analysis")
    gr.Markdown("### Powered by IBM Granite 3B Instruct")

    with gr.Tab("📝 Prescription Generator"):
        symptoms = gr.Textbox(label="Enter Symptoms")
        age = gr.Number(label="Patient Age", value=30)
        pres_btn = gr.Button("Generate Prescription")
        pres_output = gr.Textbox(label="Prescription Output")
        pres_btn.click(generate_prescription, [symptoms, age], pres_output)

    with gr.Tab("🌐 Translation (Indian Languages)"):
        text_input = gr.Textbox(label="Enter text to translate")
        lang_select = gr.Dropdown(list(languages.keys()), label="Select language")
        trans_btn = gr.Button("Translate")
        trans_output = gr.Textbox(label="Translated Text")
        trans_btn.click(translate_text, [text_input, lang_select], trans_output)

    with gr.Tab("🩻 Image Analysis"):
        img_input = gr.Image(label="Upload medical image", type="filepath")
        img_btn = gr.Button("Analyze Image")
        img_output = gr.Textbox(label="Image Analysis Result")
        img_btn.click(analyze_image, img_input, img_output)

app.launch()